apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  selector:
    matchLabels:
      name: pacman
  replicas: 1
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: myimagetosed
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
